### ISSUE TITLE
Bad next line in urxvt

### ISSUE THREAD

**Issue by IGLOU-EU** [muesli/duf#122] opened 2021-04-05 13:03 UTC
Like #120 and #84 

Build from latest commit with :   
```
go install github.com/muesli/duf@latest
```
```
> cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux

> uname -a
Linux Arrakis 5.10.19-1-lts #1 SMP Fri, 26 Feb 2021 11:11:40 +0000 x86_64 GNU/Linux

> duf -version
duf (built from source)
```

![scr_150204](https://user-images.githubusercontent.com/15379333/113576499-f3996100-961f-11eb-941b-2b2f2276bc95.png)

**Comment by muesli** [comment] 2021-04-05 13:29
Seems to be a dupe of #120 and I can't reproduce this with duf@master. I'm guessing it's somehow not building the latest duf.

**Comment by IGLOU-EU** [comment] 2021-04-05 16:30
Nop, this is the latest (From 4h ago), no problem before ^^

**Comment by muesli** [comment] 2021-12-19 18:44
Just a heads up, looks like this was a regression in urxvt, which should be fixed in its latest release.

**Closed by muesli** 2021-12-19 18:44 UTC
