### ISSUE TITLE
macOS 10.15.6 panic: runtime error: makeslice: cap out of range

### ISSUE THREAD

**Issue by tweitzel** [muesli/duf#24] opened 2020-09-25 04:22 UTC
I know nothing about golang but here's the stack track:
```
pear:Movies xarph$ duf
panic: runtime error: makeslice: cap out of range

goroutine 1 [running]:
strings.(*Builder).grow(...)
	/usr/lib/go/src/strings/builder.go:68
strings.(*Builder).Grow(...)
	/usr/lib/go/src/strings/builder.go:82
strings.Repeat(0x115d2d1, 0x1, 0x3677d46cef821200, 0x115d2d0, 0x1)
	/usr/lib/go/src/strings/strings.go:536 +0x47b
main.barTransformer(0x1134220, 0xc00012abd0, 0xc00015e708, 0xc00010f6c0)
	/home/muesli/Sources/go/src/github.com/muesli/duf/table.go:172 +0x172
github.com/jedib0t/go-pretty/v6/table.(*Table).analyzeAndStringify(0xc00017c000, 0xc000145180, 0x13, 0x13, 0x0, 0x0, 0x0, 0x0, 0xc0001c0280, 0x13, ...)
	/home/muesli/Sources/go/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.0.4/table/table.go:314 +0x570
github.com/jedib0t/go-pretty/v6/table.(*Table).initForRenderRowsStringify(0xc00017c000, 0xc000126180, 0xe, 0x10, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, ...)
	/home/muesli/Sources/go/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.0.4/table/table.go:724 +0xf8
github.com/jedib0t/go-pretty/v6/table.(*Table).initForRenderRows(0xc00017c000)
	/home/muesli/Sources/go/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.0.4/table/table.go:704 +0x205
github.com/jedib0t/go-pretty/v6/table.(*Table).initForRender(0xc00017c000)
	/home/muesli/Sources/go/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.0.4/table/table.go:563 +0x47
github.com/jedib0t/go-pretty/v6/table.(*Table).Render(0xc00017c000, 0xc00011a140, 0x1)
	/home/muesli/Sources/go/pkg/mod/github.com/jedib0t/go-pretty/v6@v6.0.4/table/render.go:22 +0x45
main.printTable(0x115d882, 0x5, 0xc0001a6000, 0xe, 0x11, 0x1, 0xc000161ec0, 0x7, 0x7)
	/home/muesli/Sources/go/src/github.com/muesli/duf/table.go:139 +0x13e5
main.renderTables(0xc00019c000, 0x10, 0x11, 0xc000161ec0, 0x7, 0x7, 0x1, 0x0, 0x4a)
	/home/muesli/Sources/go/src/github.com/muesli/duf/main.go:78 +0x19b
main.main()
	/home/muesli/Sources/go/src/github.com/muesli/duf/main.go:184 +0x5b1
```

I installed it through homebrew.
```
pear:Movies xarph$ brew install muesli/homebrew-tap/duf
Updating Homebrew...
==> Auto-updated Homebrew!
Updated Homebrew from d9416d762a to 9fbe13c17d.
Updated 3 taps (homebrew/cask-versions, homebrew/core and homebrew/cask).
==> New Formulae
leaf                                           rustscan                                       vivid                                          webify
==> Updated Formulae
Updated 130 formulae.
==> New Casks
anka-build-cloud-registry             archi                                 craft                                 eudic-es                              multi
anka-virtualization                   cernbox                               ditto                                 loni-pipeline
==> Updated Casks

<bunch of crap omitted>

==> Tapping muesli/tap
Cloning into '/usr/local/Homebrew/Library/Taps/muesli/homebrew-tap'...
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 18 (delta 6), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (18/18), 2.74 KiB | 175.00 KiB/s, done.
Tapped 4 formulae (45 files, 31.9KB).
==> Installing duf from muesli/tap
==> Downloading https://github.com/muesli/duf/releases/download/v0.3.0/duf_0.3.0_Darwin_x86_64.tar.gz
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/297165998/5ed0e080-fee3-11ea-897b-cbb1bbdca0a8?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIW
######################################################################## 100.0%
🍺  /usr/local/Cellar/duf/0.3.0: 5 files, 2.5MB, built in 8 seconds
```

**Comment by nova77** [comment] 2020-09-25 06:49
Same on WSL2 (linux_amd64).

**Comment by muesli** [comment] 2020-09-25 13:29
Thanks for the feedback. I can only attribute this to a situation where the OS reports a mount which:

- uses more disk space than the OS claims available as total disk capacity
- uses more inodes than the OS claims are available

I've added boundary checks to both situations in git master. Any chance you can try a manual build with that? Otherwise I'll probably release a v0.3.1 and knock on wood tonight 😄

**Comment by muesli** [comment] 2020-09-26 04:59
Ok, I've just pushed a v0.3.1, which (fingers crossed, as I couldn't reproduce the issue) hopefully fixes this issue.

**Comment by tweitzel** [comment] 2020-09-27 03:49
That fixed it. I will blame APFS's purgeable space being a thought experiment. Plus I have zpools mounted over NFS and... yeah.

**Comment by muesli** [comment] 2020-09-27 08:44
Thanks for the feedback, closing this ticket then!

**Closed by muesli** 2020-09-27 08:44 UTC
Labels: bug
