### ISSUE TITLE
output is difficult to read using the common solarized/dark terminal color scheme

### ISSUE THREAD

**Issue by travis-bear** [muesli/duf#87] opened 2020-11-05 20:58 UTC
<img width="1155" alt="Screen Shot 2020-11-05 at 12 57 45 PM" src="https://user-images.githubusercontent.com/505972/98295523-8d23f000-1f66-11eb-94c1-e370c9f93e11.png">

Note the contrast for the dark blue font in the "mounted on" column

**Comment by travis-bear** [comment] 2020-11-05 21:01
I wonder if it's possible to use generic colors from the solarized palette?  Or detect the color scheme in the active terminal?

**Comment by muesli** [comment] 2020-11-06 01:52
Yeah, there's a background color detection and we could even add a solarized theme.

**Comment by muesli** [comment] 2022-02-01 00:02
The color detection and conversion should have improved and I can't reproduce this with solarized/dark in v0.7.0 anymore. I'll close this, but please let me know should you still see an issue.

**Closed by muesli** 2022-02-01 00:02 UTC
Labels: bug
