### ISSUE TITLE
TUI Broken Table

### ISSUE THREAD

**Issue by hyorigo** [muesli/duf#76] opened 2020-10-22 11:10 UTC
![image](https://user-images.githubusercontent.com/67533928/96863775-f5200400-1499-11eb-8509-c1240fb79bf1.png)

* Display OS: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
* Terminal: iTerm2 Build 3.3.12
* Terminal Profile:

![image](https://user-images.githubusercontent.com/67533928/96863924-36b0af00-149a-11eb-8f98-9df432341184.png)

**Comment by hyorigo** [comment] 2020-10-22 11:15
It seems the target OS matters. With the same terminal and profile:

For Ubuntu 18.04, it's fine:
![image](https://user-images.githubusercontent.com/67533928/96864267-bb9bc880-149a-11eb-90aa-d9b85a42e005.png)

For Ubuntu 20.04, it's broken:
![image](https://user-images.githubusercontent.com/67533928/96864334-d110f280-149a-11eb-81ac-61d3ed3e0027.png)

**Comment by RangerCD** [comment] 2020-10-22 12:38
That's exactly the same issue as what I saw on my Windows system. See https://github.com/muesli/duf/issues/56#issuecomment-706274839
Should we do the same thing for all supported system to degrade to ASCII mode in this special occasion? @muesli

**Comment by muesli** [comment] 2020-10-23 09:20
@hyorigo Are you using the official releases or is this compiled by yourself? If so, are you sure Go modules are enabled?

The reason I'm asking is that there used to be a bug in go-pretty's TableWriter, that caused exactly this behavior. It has been fixed in the meantime, though, and the dependency has been bumped in duf.

@RangerCD Maybe it's a good idea to also verify that on Windows once more. We may have to open an issue upstream otherwise. The go-pretty maintainer seems fairly responsive.

**Comment by hyorigo** [comment] 2020-10-23 18:07
@muesli  Official release, here it is:

```bash
wget https://github.com/muesli/duf/releases/download/v0.4.0/duf_0.4.0_linux_amd64.deb -O duf.deb
sudo dpkg -i duf.deb
```

**Comment by muesli** [comment] 2020-11-01 12:08
Can you try this again with `v0.5.0` please?

**Comment by RangerCD** [comment] 2020-11-16 09:36
I've experienced the same issue on one of my Linux(CentOS 7) servers.
It's not caused by any remote server system(which `duf` is installed on) setting, but local terminal setting.

I'm using `en_US.UTF-8` as my local system(Manjaro 20.2) language. And `duf` works fine with my remote server, on my local terminal emulator.
One of my colleagues is using `zh_CN.UTF-8` as his local system(Deepin 15.11) language, and `duf` table brokes with the same server, but on his terminal emulator.

So the environment variable `LANG` in each SSH session has different corresponding value when me or my colleague login to the same system.

Well, in my case, it really is the same mechanism as Windows code page issue.

**Closed** 2020-11-18 07:32 UTC
Labels: bug
